name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Read Version from manifest.yaml
        run: echo "::set-env name=VERSION::$(jq -r .version manifest.yaml)"

      - name: Create Tag
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          git tag -a "v${VERSION}" -m "Version ${VERSION}"
          git push origin "v${VERSION}"

      - name: Create Deployable Zip
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          zip -r "deployable_v${VERSION}.zip" ./path/to/build/output
