name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.4'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Read Configuration from manifest.yaml
        run: |
          PRODUCTION=$(jq -r .production manifest.yaml)
          echo "PRODUCTION=$PRODUCTION" >> $GITHUB_ENV

      - name: Create Tag
        if: ${{ env.PRODUCTION == 'true' }}
        run: |
          git tag -a "v${{ github.run_number }}" -m "Production Version v${{ github.run_number }}"
          git push origin "v${{ github.run_number }}"
        
      - name: Create Deployable Zip
        if: ${{ env.PRODUCTION == 'true' }}
        run: |
          zip -r "deployable_v${{ github.run_number }}.zip" ./path/to/build/output
