name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.4'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Create Tag
        run: |
          git tag -a "v1.0" -m "Version 1.0"
          git push origin "v1.0"
        
      - name: Create Deployable Zip
        run: |
          zip -r "deployable_v1.0.zip" ./path/to/build/output
